version: '3'

services:
    docker:
        image:            docker:dind
        privileged:       true
        restart:          always
        environment:
            - DOCKER_TLS_CERTDIR=
        volumes:
            - ./data/repos/:/spug/spug_api/repos/
    spug:
        # 启动时构建
        # build: ./
        # 国内镜像镜像
        # image:            registry.cn-beijing.aliyuncs.com/hteen/docker-spug
        image:            hteen/docker-spug
        privileged:       false
        restart:          always
        depends_on:
            - docker
        ports:
            - "8080:80"
        volumes:
            - ./data/db/:/spug/spug_api/db/
            - ./data/repos/:/spug/spug_api/repos/
            - ./data/logs/:/spug/spug_api/logs/